### ISSUE TITLE
[MELHORIA] Naming no Projeto Zoo Functions

### ISSUE THREAD

**Issue by isaacbatst** [betrybe/sd-0x-project-zoo-functions#12]
Bloco: 08
Dia: 5
Melhoria em:

- [X] Projeto

**Comment by isaacbatst** [comment]
Baseado [nessa thread](https://betrybe.slack.com/archives/C010RP4341Y/p1602264655079600)

Gente, tudo bom? Pensando aqui para as próximas turmas,  uma possível refatoração do projeto para usar o termo espécies ao invés do termo animals para melhorar o entendimento.

Percebi que usar animals gera uma ambiguidade: estamos falando dos animais chamados de residents (array com cada leão, por ex.) ou da espécie como um todo?

Isso se aplicaria tanto para a entrada no objeto exportado pelo data.js  como para as funções que lidam com essa entrada.

**Comment by isaacbatst** [comment]
Criei um PR ajustando isso e aproveitando para fazer uma melhoria nos nomes das funções no geral: nomeando-as com verbos, por exemplo: `animalsByIds` virou `getSpeciesByIds`

### IMPORTANTE
NOMES DE ARQUIVO E DESCRIÇÕES NO `requirements.json` FORAM ALTERADOS, ESSAS MUDANÇAS DEVERAM SER REFLETIDAS NO `sd-0x-project-zoo-functions-tests` E NO FOREST

**Comment by isaacbatst** [comment]
Como são várias alterações é importante testarmos bem, caso mergeado

**Comment by isaacbatst** [comment]
Criei o [PR](https://github.com/betrybe/sd-0x-project-zoo-functions-tests/pull/7/) no repositório de testes também

**Comment by roziscoding** [comment]
Boa, @isaacbatst!
@mariocmachado tá no seu radar pra colocarmos os demais ajustes numa próxima sprint?
